### ISSUE TITLE
Consider a release?

### ISSUE THREAD

**Issue by ryanmcnamara** [lthibault/jitterbug#1]
Hi, thanks for the library. Would you consider releasing? 
Dep works much better with libraries that have releases (tags), might help people adopt.

Thanks!

**Comment by lthibault** [comment]
@ryanmcnamara [Done](https://github.com/lthibault/jitterbug/releases/tag/v1.0)!

Out of curiosity, what is your use-case for jitterbug?

**Comment by ryanmcnamara** [comment]
I've got a service that performs a bunch of async tasks
I want it to perform all the tasks at some interval (say 30 seconds), but i don't want all the tasks to start at the exact same instant for cpu reasons

**Comment by ryanmcnamara** [comment]
Thanks a bunch!
