### ISSUE TITLE
Normal distribution API seems broken

### ISSUE THREAD

**Issue by egorse** [lthibault/jitterbug#2]
Next code generates delay of minutes instead of second +- 

```
package main

import (
	"fmt"
	"time"

	"github.com/lthibault/jitterbug"
)

func main() {
	j1 := jitterbug.Norm{Stdev: time.Nanosecond * 100}
	d1 := j1.Jitter(1 * time.Second)
	fmt.Printf("%v\n", d1)
}
```

**Comment by lthibault** [comment]
Hi @egorse thanks for bringing this up.

If you have a fix, I can take a look at it today and get it merged quickly.  If not, it may take a while to get to it.

Cheers,
Louis

**Comment by lthibault** [comment]
@egorse Many thanks for the patch.

Out of curiosity, what is your use-case for jitterbug?

**Comment by egorse** [comment]
@lthibault  we were trying to replicate rare problems one of customers has with PTP and tried to insert jitter to see how the control loop behave. sorry for late reply

**Comment by lthibault** [comment]
@egorse No worries, thanks for the feedback.  I hope this library was helpful in solving the problem.
