### ISSUE TITLE
Uniform jitter has unexpected behavior

### ISSUE THREAD

**Issue by zenhorace** [lthibault/jitterbug#4]
I thought I'd mention this in case anyone else felt the same. The behavior of uniform jitter is unintuitive.
Let say I set a min of 30s and then call `Jitter` with a duration of 60s. The results aren't uniform. Since half the values will fall below the min, I'd have a 0.5 probability of a 30s duration being returned to me. I would think that the expected behavior here is to have uniform distribution in the range [30, 60) and have the probabilities of that range sum to 1.

So I forked and made [changes](https://github.com/hfacey/jitterbug/commit/f6297a83634abc5aa0be094ff7503ed8b7cbed3b) to the behavior. Here, the user instead specifies a `MaxJitter` instead of a min, that the `Jitter` function now jitters _about_ the provided duration. So lets say I supply a `MaxJitter` of 10s and call `Jitter` with a duration of 60s. The duration returned is uniformly distributed over the [50, 70) and those probabilities sum to 1. I think this is more intuitive/desired behavior.
This brings the behavior inline with that of normally distributed Jitter.

If you agree, I can contribute the change back to this repo. If not, no worries. Either way I'd like to hear your thoughts. Love the name of this repo btw 😀

**Comment by lthibault** [comment]
@hfacey Thanks for flagging this!  I really appreciate you bringing this to my attention.

I think I partly agree.  `Min` should definitely not bias the output in the way it does, but I disagree that uniform sampling should be centered on the duration.  I see how this behavior could cause surprise, but it makes sense from the point of view of the distribution's semantics. Drawing from a uniform distribution gives you a **positive** number, whereas drawing from a normal distribution can return negatives.  In practice, this drives very different usage patterns:

| Distribution | Sign | Usage | 
| -- | -- | --|
| Uniform | + | randomize *up to* `d` |
| Normal | + / - | randomize *around* `d` |

If we fix the behavior of `Min` to uniformly distribute ticks between `Min` and `d`,  you can center on a duration of your choice, *x*, by setting `min=m` and `d=x+(x-m)`.  At any rate, `Min` is the real culprit, here.

If you want to open a PR, I'll happily merge it 🙂 .  This will call for a major version bump.

-----
P.S:  I'm glad you like the name.  I was feeling inspired that day! 😄

**Comment by zenhorace** [comment]
Cool! That behavior would also make sense - essentially getting a uniform distribution over the range [min, d), which is just as easy to use. After work today, I'll fix the issue with `Min` biasing the output and submit a PR 👍🏽

**Comment by lthibault** [comment]
@hfacey Awesome!  Thanks!

**Comment by lthibault** [comment]
@hfacey When you get a chance, I'm curious to know a bit more about what you're building with jitterbug.  Can you tell me a bit about the problem domain and the reasoning that led you to use jittered tickers?  This is 80% user-feedback and 20% pure curiosity on my part. 🙂

**Comment by lthibault** [comment]
In the end I decided to make this a minor release, since the `Min` behavior was poorly specified and the implementation is likely to have departed from user's expectations.  (Basically, I'm treating this as a bugfix.)

Thanks again for bringing this to my attention, and for submitting the fix!

**Comment by lthibault** [comment]
In the end I decided to make this a minor release, since the `Min` behavior was poorly specified and the implementation is likely to have departed from user's expectations.  (Basically, I'm treating this as a bugfix.)

Thanks again for bringing this to my attention, and for submitting the fix!

**Comment by zenhorace** [comment]
It's just kind of a random personal project 😅. I'm testing the filtering/detection capabilities of a server. Lets say a say I'm serving web traffic, and the vast majority of the requests are "good" but a handful are "bad" and I need to detect/filter those. But I can't rely on typical ID info such as IP address because it either changes, is unavailable, or is common with a  large number of "good" requests. Can my server learn to filter the bad requests while minimizing the impact to good requests? Turns out if bad requests hit the server with a regular cadence (say with a `time.ticker`) it can easily filter on the fly with minimal impact to "good" traffic 😂 so I had to find a jittered ticker to make the problem less trivial. And that's how I found jitterbug.

**Comment by zenhorace** [comment]
and yeah, my pleasure. and I agree it should only be a minor release as it doesn't actually break any API logic. it is essentially a bug fix

**Comment by lthibault** [comment]
@hfacey Thanks for the explanation -- that sounds like a really cool project, actually!  I'm guessing you're implementing some kind of machine-learning (or other statistical) approach?

At any rate, I hope this package makes your life easier. 🙂
