### ISSUE TITLE
go.mod dependency github.com/lthibault/jitterbug v2.0.0+incompatible

### ISSUE THREAD

**Issue by mikeyrcamp** [lthibault/jitterbug#6]
Jitterbug has both a v1 and v2 version, but the current go.mod file's path needs a /v2 appended to the end to follow the go.mod spec and a new version tagged (e.g. v2.2.2). Due to it not properly following the go.mod spec I cannot retrieve the latest v2.2.1 and instead get and older copy with the following dependency in my go.mod `v2.0.0+incompatible`

current go.mod
```
module github.com/lthibault/jitterbug

go 1.14
```

fixed go.mod following the go modules spec then followed with a new release v2.2.2 tag
```
module github.com/lthibault/jitterbug/v2

go 1.14
```

**Comment by lthibault** [comment]
@mikeyrcamp Thanks for the heads-up!  Any chance you could submit a PR for this?

**Comment by mikeyrcamp** [comment]
Will do, just have to get company permission first so it may be a few days. I appreciate the uber fast response!

**Comment by lthibault** [comment]
@mikeyrcamp Can I get a quick sense-check from you on #7 ?  It should take no more than 2 minutes.
